# Generated by Django 5.2.4 on 2025-07-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repicuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
