# Generated by Django 5.2.4 on 2025-07-29 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0002_repicuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='repicuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mobile', 'Mobile Phones'), ('furniture', 'Furniture'), ('electronics', 'Electronics & Appliances'), ('fashion', 'Fashion'), ('books', 'Books, Sports & Hobbies'), ('pets', 'Pets')], max_length=30)),
                ('subcategory', models.CharField(choices=[('mobile_phones', 'Mobile Phones'), ('accessories', 'Accessories'), ('tablets', 'Tablets'), ('sofa_dining', 'Sofa & Dining'), ('beds_wardrobes', 'Beds & Wardrobes'), ('home_decor', 'Home Decor & Garden'), ('kids_furniture', 'Kids Furniture'), ('other_household', 'Other Household Items'), ('tvs', 'TVs, Video - Audio'), ('kitchen_appliances', 'Kitchen & Other Appliances'), ('computers', 'Computers & Laptops'), ('cameras', 'Cameras & Lenses'), ('games', 'Games & Entertainment'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('books', 'Books'), ('gym', 'Gym & Fitness'), ('instruments', 'Musical Instruments'), ('sports', 'Sports Equipment'), ('hobbies', 'Other Hobbies'), ('fishes', 'Fishes & Aquarium'), ('pet_food', 'Pet Food & Accessories'), ('dogs', 'Dogs'), ('other_pets', 'Other Pets')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('location_state', models.CharField(blank=True, max_length=50, null=True)),
                ('location_city', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
