# Generated by Django 5.2.4 on 2025-07-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0003_repicuser_profile_picture_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='repicuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repicuser',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
